spring.application.name=bank
spring:
datasource:
url: jdbc:postgresql://localhost:5432/bankcard_db
username: admin
password: 1234
driver-class-name: org.postgresql.Driver
jpa:
hibernate:
ddl-auto: validate
properties:
dialect: org.hibernate.dialect.PostgreSQLDialect
format_sql: true
jdbc:
batch_size: 20
show-sql: false
liquibase:
change-log: classpath:db/changelog/db.changelog-master.yaml
enabled: true

app:
jwt-secret: "mySecretKey12345678901234567890123456789012345678901234567890"
jwt-expiration-milliseconds: 86400000
encryption-key: "1234567890123456"

server:
port: 8080

springdoc:
api-docs:
swagger-ui:
path: /swagger-ui.html
operations-sorter: method
tags-sorter: alpha

logging:
level:
ru.effectivemobile: DEBUG
org.springframework.security: DEBUG